Update for current versions:
- Git updated to 2.9.0
- Mercurial updated to 3.8
- Docker updated to 1.11.0
- Switch to statically compiled docker

diff --git a/packages/git/packaging b/packages/git/packaging
--- a/packages/git/packaging
+++ b/packages/git/packaging
@@ -1,8 +1,57 @@
-set -e -x
+exec 2>&1
 
-tar xzf git/git-1.7.11.2.tar.gz
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
+set -x
 
-cd git-1.7.11.2
-./configure --prefix=${BOSH_INSTALL_TARGET}
-make NO_TCLTK=Yes NO_PYTHON=Yes
-make NO_TCLTK=Yes NO_PYTHON=Yes install
+# Detect # of CPUs so make jobs can be parallelized
+CPUS=$(grep -c ^processor /proc/cpuinfo)
+
+# Available variables
+# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
+# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
+
+# autoconf
+export PREFIX=${BOSH_INSTALL_TARGET}
+export PATH=$PREFIX/bin:$PATH
+export HOME=/home/vcap
+
+tar xzf autoconf-2.69.tar.gz
+(
+  set -e
+  cd autoconf-2.69
+  autoconf_dir=$PREFIX/share/autoconf ./configure --prefix=$PREFIX
+  make -j${CPUS}
+  make install prefix=$PREFIX
+)
+
+# automake
+tar xzf automake-1.15.tar.gz
+(
+  set -e
+  cd automake-1.15
+  ./configure --prefix=$PREFIX
+  make -j${CPUS}
+  make install prefix=$PREFIX
+)
+
+# libtool
+tar xzf libtool-2.4.6.tar.gz
+(
+  set -e
+  cd libtool-2.4.6
+  ./configure --prefix=$PREFIX
+  make -j${CPUS}
+  make install prefix=$PREFIX
+)
+
+tar xzfz git-2.9.0.tar.gz
+(
+  set -e
+  cd git-2.9.0
+  make configure
+  ./configure --prefix=${BOSH_INSTALL_TARGET}
+  make NO_TCLTK=Yes -j${CPUS}
+  make NO_TCLTK=Yes install
+)
+
